### ISSUE TITLE
Cannot setup any Schedule

### ISSUE THREAD

**Issue by Brammetjeboterhammetje** [vingerha/gtfs2#104]
**What is my Problem?**
I cannot create a route, It will say that the Start/End destination is Incorrect. 

![{ACC864B5-C935-4550-B1F9-1B80A13F4608}](https://github.com/user-attachments/assets/ecf60638-3522-48c7-bda9-dacde3e642c7)

**What did I do??**
Its a fresh installation, I installed the https://gtfs.ovapi.nl/nl/NL-20240911.gtfs.zip 
The menu looks different than at the screenshots (What is 99 and 2)

![{132B7AD6-85B7-4FC0-86E8-28C2ADD49DE7}](https://github.com/user-attachments/assets/fe6d1263-fa0a-4892-857f-9709db79cc3a)

or what is 0 and 1?

![{991A044C-DE0E-4134-AA30-775E330D830D}](https://github.com/user-attachments/assets/c5834634-aa77-4b0b-ad93-b8af3d83cdb8)

I have tried all options, reinstalling it and also testing a few routes and diffrent directions. Nothing seems to work and always will result into the error Start/End direction incorrect

Sorry if my english is bad, It is not my main language.

**Comment by vingerha** [comment]
The menu is an issue with the latest HA, and they are awaiting a fix 'soon' 
99 is 'non train', 2 is train
0 is out, 1 is return
But...the real challenge is the route and there are many reasons why it cannot find it, ost common is that there are no vehicles driving today and since you entered this before midnight, that sounds like an option. Then on the start/end, try it out with two stops that are next to one another as well so that you know 'something' is working.
