### ISSUE TITLE
[FEATURE]: Add back button to setup screens

### ISSUE THREAD

**Issue by DeflateAwning** [vingerha/gtfs2#26]
**Describe the solution you'd like**
A back button alongside the "Submit" button would be very helpful.

**Describe alternatives you've considered**
Currently you have to start over if you misclick.

**Additional context**
This came up because I wasn't sure which route number was inbound, and which was outbound, and I picked the wrong one.

**Comment by vingerha** [comment]
If you can explain how to EASILY do that ... I would love to.... the config_low is already not that easy to test
I see the same challenges on my side but I that is because I am using this a lot for testing
As this is usually a one-off setup for the average user, I donot want to spend a lot of time on it ;)

**Comment by vingerha** [comment]
Veified with the dev's and there is no such thing in the current config flow to go 'back'
Closing this a technically ( currently ) not feasible from the HA custom app integration pov

**Comment by DeflateAwning** [comment]
Hmm that's too bad; is there a way to have all the config on one screen, with dynamic hiding/showing of fields based on what's selected?
