### ISSUE TITLE
GTFS2 Broken after upgrade to Homeassistant 2024.5.

### ISSUE THREAD

**Issue by huggenknubbel** [vingerha/gtfs2#69]
**Describe the bug**
after upgrading to 2024.5 i noticed some strange behavior of the Dashboard Cards which shows mu Bus station next to me. 
I tried a restart but HA doesn't come up again. 
So i deleted the GTFS2 out of custom components and delete the integration and all entitys. 
Tried to Reinstall via HACKS which seems to work.
After tried to add the GTFS2 integration i got the Error below.

**Release used**
HA: 2024.5
GTFS2: 0.4.5.3

**Additional**
```
Logger: homeassistant.setup
Quelle: setup.py:248
Erstmals aufgetreten: 09:54:29 (1 Vorkommnisse)
Zuletzt protokolliert: 09:54:29

Unable to set up dependencies of 'gtfs2'. Setup failed for dependencies: ['zone, person']
```

**Comment by huggenknubbel** [comment]
i found this breaking change in 0.4.5.3 [https://github.com/home-assistant/core/pull/114484](https://github.com/home-assistant/core/pull/114484)

**Comment by vingerha** [comment]
Thanks for reporting it and I now see this too. I remove the release for now....very sorry for a stupid typo

Since the HA instance no longer starts you can edit the /config/custom_components/gtfs2/manifest.json to look like this

![image](https://github.com/vingerha/gtfs2/assets/44190435/7fcd4e20-69e4-4e20-9396-fa70535db86d)

**Comment by vingerha** [comment]
Closing as resolved with new release-update and instruction.
