### ISSUE TITLE
no Realtime data after configuring stop/RT data

### ISSUE THREAD

**Issue by CityDweller** [vingerha/gtfs2#93]
After setting up a new stop, select configure to add RT information.
See Issue 92 for data on setting up the stop

Here is the RT data I added:
TripUpdates: https://gtfsrealtime.ridetransit.org/GTFSRealTime/TripUpdate/Tripupdates.pb
VehiclePosition: https://gtfsrealtime.ridetransit.org/GTFSRealTime/Vehicle/VehiclePositions.pb
Alerts: https://gtfsrealtime.ridetransit.org/GTFSRealTime/Alerts/Alerts.pb

Refresh and interval both set to 30 minues
<img width="962" alt="2024-06-16 (1)" src="https://github.com/vingerha/gtfs2/assets/2804911/1b7d001d-0da4-43b6-a7ba-4f8fa8b44b42">

**Comment by vingerha** [comment]
So what you are saying is that you have no realtime data visible.
The vehicle will only show in www/gtfs2 ... if any
The alerts will show 'if any'...usually nothing to alert on I guess
For the next departures...this depends on the provider, you can use the service call to extract a readable version (see docu) and analyse if that contains a realtime stamp for your stop.

**Comment by CityDweller** [comment]
I used the service call and did get data for TripUpdates, VehiclePosition, and Alerts.

The next RealTime information doesn't sow in the attributes of the route I configured; is this an improper expectation.

**Comment by vingerha** [comment]
Next realtime departure: you would have to do the mapping in order to see if it has the right data, both static and realtime need to have the stop_id ... and for the same trip id OR (!) for the same route+direction, use the service call with debug-output to have it readable. I myself can not do the analysis, but although there are plenty people with working RT, I will also not say that the code covers all cases. ....so I will act if you can prove the data is there but not mapped :)
Quite often they are not provided (correctly)

**Comment by vingerha** [comment]
Closed as no further feedback
